# -*- coding: utf-8 -*-
"""Worksheet1_2507012_LinaGiri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DS0NOlY9yMfkptXPYGsOsS6D1Qgln85Y

4.1 WarmingUpExercise: Basic Vector and Matrix Operation with Numpy

Problem- 1: Array Creation
"""

import numpy as np

empty_array = np.empty((2, 2))
print("Empty array 2x2:\n", empty_array)

ones_array = np.ones((4, 2))
print("\nAll ones array 4x2:\n", ones_array)

filled_array = np.full((3, 3), fill_value=7, dtype=int)
print("\nArray filled with 7:\n", filled_array)

given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros array like given array:\n", zeros_like_array)

ones_like_array = np.ones_like(given_array)
print("\nOnes array like given array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nNumpy array from list:\n", array_from_list)

""" Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:"""

import numpy as np

arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", arr1)

arr2 = np.arange(9).reshape((3, 3))
print("\n2. 3x3 matrix 0 to 8:\n", arr2)

identity_matrix = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_matrix)

random_arr = np.random.random(30)
mean_value = random_arr.mean()
print("\n4. Random array of size 30:\n", random_arr)
print("Mean of the array:", mean_value)

random_matrix = np.random.random((10, 10))
min_val = random_matrix.min()
max_val = random_matrix.max()
print("\n5. 10x10 random matrix:\n", random_matrix)
print("Min value:", min_val, "Max value:", max_val)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero array with 5th element as 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:\n", reversed_arr)

n, m = 5, 5
border_array = np.ones((n, m))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)

checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 checkerboard pattern:\n", checkerboard)

"""Problem- 3: Array Operations:"""

import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_xy = x + y
print("1. x + y:\n", add_xy)

sub_xy = x - y
print("\n2. x - y:\n", sub_xy)

mul_x = x * 3
print("\n3. x * 3:\n", mul_x)

square_x = x ** 2
print("\n4. Square of x:\n", square_x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5. Dot products:")
print("v . w =", dot_vw)
print("x . v =", dot_xv)
print("x . y =\n", dot_xy)

concat_row_xy = np.concatenate((x, y), axis=0)
concat_col_vw = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("\n6. Concatenations:")
print("x and y along row:\n", concat_row_xy)
print("v and w along column:\n", concat_col_vw)

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
print("\n7. Concatenate x and v error:\n", concat_xv_error)

"""Problem- 4: Matrix Operations:

Given arrays
"""

import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

""" 1. Prove A.A−1 = I."""

A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A_inv =\n", identity)

"""2. Prove AB̸ = BA."""

AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

"""3. Prove (AB)T = BTAT"""

AB_T = np.dot(A, B).T
B_TA_T = np.dot(B.T, A.T)

print("\n(AB)^T =\n", AB_T)
print("B^T A^T =\n", B_TA_T)
print("Are they equal?", np.array_equal(AB_T, B_TA_T))

"""Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9
 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
 of Numpy}

Step 1: Represent in matrix form AX = B
"""

import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("1. A * A_inv =\n", identity)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

AB_T = np.dot(A, B).T
B_TA_T = np.dot(B.T, A.T)
print("\n3. (AB)^T =\n", AB_T)
print("B^T * A^T =\n", B_TA_T)
print("Are they equal?", np.array_equal(AB_T, B_TA_T))

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])

B_sys = np.array([-1, -3, 9])